### ISSUE TITLE
Issue with COH series

### ISSUE THREAD

**Issue by calebthewood** [UHERO/data-portal#245]
attempting to visit [coh/category?id=4437&data_list_id=5952](https://data.uhero.hawaii.edu/coh/#/category?id=4437&data_list_id=5952)

loader hangs, console shows:

```
ERROR TypeError: Cannot read properties of undefined (reading 'handle')
    at SwitchMapSubscriber.project (category-helper.service.ts:80:100)
    at SwitchMapSubscriber._next (switchMap.js:28:27)
    at SwitchMapSubscriber.next (Subscriber.js:49:18)
    at SwitchMapSubscriber.notifyNext (switchMap.js:66:26)
    at SimpleInnerSubscriber._next (innerSubscribe.js:10:21)
    at SimpleInnerSubscriber.next (Subscriber.js:49:18)
    at Object.complete (forkJoin.js:50:40)
    at Object.wrappedComplete (Subscriber.js:166:62)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183:16)
    at SafeSubscriber.complete (Subscriber.js:168:26)
```

**Comment by vcward** [comment]
The error is with "Public School - Student Characteristics" category where the default geography is set to Hawaii County (indicated by "HAW" in the brackets). <img width="964" alt="Screenshot 2024-03-13 at 2 20 59 PM" src="https://github.com/UHERO/data-portal/assets/12493326/b0b5d1f9-a631-4876-9f2a-21c8f2d2baed">
Console log of cachedCategoryData:
<img width="509" alt="Screenshot 2024-03-13 at 2 33 09 PM" src="https://github.com/UHERO/data-portal/assets/12493326/e214d293-7cab-41d3-a4cc-88c34a913129">

If you go into the data list (COH_Education_PSStudentCharacteristics), each of the measurements only contain 1 series where the geography is the State of Hawaii. The portal currently relies on either the default geo/freq set in Udaman or a geo/freq specified in URL parameters; so based on the default set in Udaman, it can't find the right region to select.
Could just fix the setting in Udaman, but the data portal should have a better fall back than hanging on loading icon.
